4주차 코드리뷰 PR
kakao-tech-campus-2nd-step3/Team18_FE pull request #14
Opened 2024-09-26 14:55 UTC by kang-kibong

이번에 4주차 작업을 하면서 궁금한 내용들을 `README.md`에 기재하였습니다!

감사합니다! 🙇‍♂️

2024-10-06 06:51 UTC, JunilHwang requested changes
README.md 에 대한 부분은 관련된 코드에 코멘트 남겨놨으니 확인 부탁드립니다 🙏

Modal의 경우 headless ui 가 구성한 방식을 참고하시면 좋을 것 같아요.
질문주신 것 처럼 지금은 책임이 흩어져있습니다.
modal에 onClose 라는 이벤트가 있긴 한데, 실제로 close라는 행위는 모달이 하고 있지 않아요.
바깥에서 close를 해주고 있습니다.
적합한 이름이 아닌거죠 ㅎㅎ

```tsx
<AlertDialog.Root>
	<AlertDialog.Trigger>
		<Button color="red">Revoke access</Button>
	</AlertDialog.Trigger>
	<AlertDialog.Content maxWidth="450px">
		<AlertDialog.Title>Revoke access</AlertDialog.Title>
		<AlertDialog.Description size="2">
			Are you sure? This application will no longer be accessible and any
			existing sessions will be expired.
		</AlertDialog.Description>

		<Flex gap="3" mt="4" justify="end">
			<AlertDialog.Cancel>
				<Button variant="soft" color="gray">
					Cancel
				</Button>
			</AlertDialog.Cancel>
			<AlertDialog.Action>
				<Button variant="solid" color="red">
					Revoke access
				</Button>
			</AlertDialog.Action>
		</Flex>
	</AlertDialog.Content>
</AlertDialog.Root>
```

이게 radix-ui 에서 제공하는 방식인데, close(cancel)에 대한 기능을 컴포넌트로 제공하고 있습니다.
이런걸 headless ui 라고 부른답니다. ui가 기능을 가지고 있는거죠.

2024-10-06 06:51 UTC, JunilHwang commented on package.json
> +    "tsc": "tsc --noEmit --project ./tsconfig.json",
tsc를 실행하면 이런 오류가 발생하네요 ㅎㅎ 

```bash
> team18-fe@0.0.0 tsc
> tsc --noEmit --project ./tsconfig.json

src/routes/path.ts:8:10 - error TS1005: ';' expected.

8   Recruit: '/recruit',
           ~

src/routes/path.ts:9:20 - error TS1005: ';' expected.

9   VISA_REGISTRATION: '/visa-registration',
                     ~

src/routes/path.ts:10:14 - error TS1005: ';' expected.

10   POST_NOTICE: '/post-notice',
                ~

src/routes/path.ts:12:1 - error TS1109: Expression expected.

12 } as const;
   ~

src/routes/path.ts:12:3 - error TS1434: Unexpected keyword or identifier.

12 } as const;
     ~~


Found 5 errors in the same file, starting at: src/routes/path.ts:8


Process finished with exit code 2

```

2024-10-06 06:51 UTC, JunilHwang commented on package.json
> +    "tsc": "tsc --noEmit --project ./tsconfig.json",
PR 올릴 때 lint 검사 할 수 있도록 추가해보세요! 

github actions 추가해서 확인해볼 수 있답니다~

2024-10-06 06:51 UTC, JunilHwang commented on package.json
>      "dev": "vite",
<img width="1747" alt="image" src="https://github.com/user-attachments/assets/b422eba8-3bfd-4b94-83e8-5052f62ec34a">


개발서버 실행하니까... 오류가 발생해요... ㅠ

2024-10-06 06:51 UTC, JunilHwang commented on package.json
>      "dev": "vite",
이제보니.. 해당 파일이 아예 없군요 ㅋㅋ;

2024-10-06 06:51 UTC, JunilHwang commented on src/routes/path.ts
> +} as const;
이런 코드가 커밋이 되었네요...?

```suggestion
const ROUTE_PATH = {
  HOME: '/',
  Recruit: '/recruit',
  VISA_REGISTRATION: '/visa-registration',
  POST_NOTICE: '/post-notice',
  AUTH,
} as const;

export default ROUTE_PATH;
```

이렇게 쓰여야 하는게 아닐까요?

2024-10-06 06:51 UTC, JunilHwang commented on package.json
>      "dev": "vite",
개발서버가 아니라 storybook 을 통해서 결과물을 확인할 수 있군요...

리뷰 요청하실 때 어떤 방식으로 결과물을 확인할 수 있는지 정도는 남겨주세요.. ㅠ

2024-10-06 06:51 UTC, JunilHwang commented on src/pages/recruit/RecruitCard.tsx
> +import instagram from '@assets/styles/images/features/layout/footer/instagram_Icon.svg';
```suggestion
import instagram from '@assets/icons/social/instagram.svg';
```

이렇게 변경되어야할 것 같네요.. ㅎㅎ

path alias를 굳이 써야하는 이유가 있을까요?
지금처럼 소스코드 추적도 잘 안 되는 상황이다보니..

2024-10-06 06:51 UTC, JunilHwang commented on src/pages/recruit/RecruitCard.tsx
> +import { RecruitCardProps } from './index';
index에서 RecruitCard를 가져다 사용하는데
다시 RecuritCard 가 index를 가져와서 사용하고 있습니다.
순환 참조가 발생하는거죠...
이런 부분은 다 찾아서 고쳐주세요.

2024-10-06 06:51 UTC, JunilHwang commented on src/pages/recruit/RecruitCard.tsx
> +import { RecruitCardProps } from './index';
props를 index가 아니라 이 파일이 가지고 있어야 하는거 아닐까요?

2024-10-06 06:51 UTC, JunilHwang commented on src/components/common/Modal/index.tsx
지금 모든 컴포넌트가 index.tsx에 정의되어 있는 상태에요.

그런데 Components/comon에 보면 index가 컴포넌트가 아니라 export를 해주고 있습니다.
다른 사람 입장에서 컴포넌트를 탐색할 때 너무 헷갈리지 않을까요?

2024-10-06 06:51 UTC, JunilHwang commented on src/components/common/Modal/index.tsx
> +} & React.HTMLAttributes<HTMLDivElement>;
```tsx
export type Props = {
  textChildren: ReactNode;
  buttonChildren: ReactNode;
  borderRadius?: string;
  onClose: () => void;
} & ComponentProps<'div'>
```

이렇게 표현할 수 있답니다!

2024-10-06 06:51 UTC, JunilHwang commented on src/components/common/Modal/index.tsx
> +    <Overlay onClick={onClose}>
여기서 onClose 라는 이름이 적합할까요?

onClose의 의미는 'close가 되었을 때 실행되는 이벤트' 입니다.
그런데 지금은 아무리 봐도 close를 바깥에서 해주는 것 같네요 ㅎㅎ
이럴 때는 `onOverlayClick` 으로 표현해야 적합할 것 같아요.

이벤트는 "특정 행위가 발생했을 때 알려주는 것" 인데, 지금은 "행위를 해라!" 라고 명령하는 느낌입니다. 역할과 이름이 일치하지 않는거죠.

2024-10-06 06:51 UTC, JunilHwang commented on src/components/common/Modal/index.tsx
> +  buttonChildren: ReactNode;
> Modal 컴포넌트를 구현하면서 텍스트 부분과 버튼 부분에 들어갈 내용은 개발할 때 코드를 작성하는 사람이 자유롭게 작성하여 구성할 수 있도록 textChildren과 buttonChildren만으로 구성하였는데, 더 적합하거나 지향하는 방식이 있을까요?

지금은 일단 이렇게 표현하는게 좋아보여요.
물론 더 좋은 방법이 있긴 하지만, 신경써야 할 부분이 무척 많답니다 ㅎㅎ

예시 코드를 보여드리자면...


```tsx
<Modal>
  <Modal.Text>여기에는 Text와 관련된 내용이 쌓이게 됩니다.</Modal.Text>
  <Modal.Button>여기에는 Button과 관련된 내용이 쌓이게 됩니다.</Modal.Button>
  <Modal.Text>여기에는 Text와 관련된 내용이 쌓이게 됩니다.</Modal.Text>
  <Modal.Button>여기에는 Button과 관련된 내용이 쌓이게 됩니다.</Modal.Button>
</Modal>
```

이렇게 표현한 다음에 Text로 수집한 것들과 Button으로 수집한 것들을 컴포넌트에서 자체적으로 처리해주는거죠.

그치만 지금 방식처럼 간단하게 구현해도 무방해보입니다!

2024-10-06 06:51 UTC, JunilHwang commented on src/components/common/Modal/index.tsx
> +        </Wrapper>
그리고 그냥 이걸 chidlren으로 넣어주고
나머지 영역은 바깥에서 조립하도록 만드는 것도 나쁘지 않아요.
headless ui 를 생각해보시면 좋습니다.

modal이 ui에 대한 책임은 최소화하고, 기능만 제공하는거죠 ㅎㅎ

https://www.radix-ui.com/themes/docs/components/alert-dialog

참고해보세요!

2024-10-06 06:51 UTC, JunilHwang commented on src/features/layout/Header/index.tsx
> +          </Button>
이렇게 주입하는 방식은 좋습니다.
다만 Button의 css에 넘겨주는 값은 리액트의 렌더링 라이 프사이클과 전혀 무관합니다.
상수로 만들어서 관리해도 되는거죠 ㅎㅎ
불필요하게 css에 대한 선언이 렌더링이 될 때 마다 발생하고 있을꺼에요.

불필요한 연산을 하지 않도록 상수로 만들어서 관리해주세요!

2024-10-06 06:51 UTC, JunilHwang commented on src/hooks/useToggle.ts
> +  const [isToggle, setIsToggle] = useState<boolean>(false);
```tsx
  const [isToggle, setIsToggle] = useState(false);
```
어차피 타입은 추론될 것 같네요.

2024-10-06 06:51 UTC, JunilHwang commented on src/hooks/useToggle.ts
> +export default useToggle;
```tsx
const useToggle = (): [boolean, () => void] => {
  const [enable, setEnable] = useState<boolean>(false);

  const toggle = () => setEnable((prev) => !prev);

  return [enable, toggle];
};

export default useToggle;
```
`isToggle` 이란 표현은 어색해요. toggle 상태인지 검사하는 함수로 생각될 수 있습니다.
enable 처럼 명시적인 표현이 훨씬 좋아요.
아니면 `value` 라고 표현하거나?

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/helpers/responsive.ts
> +});
여기있는게 어째서 assets일까요..?

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/helpers/responsive.ts
> +});
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/86fe0767-8a49-4f1b-a193-7d6787bb48d1">

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/helpers/responsive.ts
> +});
assets과는 전혀 무관해보여요..!

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/theme.ts
> +export default theme;
styles 에는 css가 있어야할 것 같아요. ts파일은 밖으로 보내줘야 하지 않을까요~?

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/global/breakpoints.ts
> +};
> 태블릿(768px)과 모바일(480px)에서 반응형을 고려하여 breakpoints를 정의하였고, 이를 보다 명시적으로 활용하기 위해 responsiveStyles 함수를 구현했습니다. 멘토님께서는 보통 반응형 스타일링을 구현할 때 어떤 방식을 사용하시나요? 혹시 제가 사용한 responsiveStyles 함수보다 효율적이거나 코드의 가독성을 높일 수 있는 더 나은 방법이 있을까요? 멘토님이 추천하는 방법이나 일반적으로 사용되는 best practice 또한 궁금합니다.

지금과 같은 방식도 좋아보입니다.
요즘에는 사실 반응형보단 적응형 UI로 만들고 있어요 ㅎㅎ
반응형으로 만든다는건 PC에서도 쓰고 mobile에서도 쓴다는건데  보통 PC에서 mobile ui 로 보려고 시도하는 경우는 많이 없어서요.

대신 모바일 페이지로 직접 접근해서(가령 네이버로 따지면 m.naver.com) mobile ui를 확인하곤 한답니다.

어쨌든, 지금과 같은 방식도 나쁘지 않아요!

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/global/breakpoints.ts
> +};
저희 팀의 경우 직접 구현하려기 보단 tailwindcss나 혹은 headless-ui에서 제공하는 토큰을 이용해서 breakpoint 별로 class를 별도로 적용하곤 한답니다.

그리고 주로 아예 모바일 전용 페이지나 테블릿 전용 페이지를 만들어서 따로 제공하는 방식을 제일 많이 사용해요.

반응형으로 하게 되면 모바일 콘텐츠랑 데스크톱 콘텐츠를 한 번에 가지고 있어야 하는데 이게 생각보다 리소스를 많이 사용한답니다 ㅎㅎ

특히 요즘엔 반응형 UI 구성은 grid나 flex를 이용해서 많이 표현하는 편입니다. 자잘한 토큰만 breakpoint 별로 관리하고 있어요!

2024-10-06 06:51 UTC, JunilHwang commented on src/assets/styles/global/breakpoints.ts
> +};
best practice 보다는 "이럴 땐 이게 좋더라" 정도로 받아들여주시면 좋을 것 같습니다. 사실 일반적인 방법이라는게.. 딱히 없어요 ㅋㅋ

2024-10-08 00:39 UTC, merged

2024-10-08 08:35 UTC, YIMSEBIN commented on package.json
>      "dev": "vite",
다음부터 storybook 링크도 함께 남기도록 하겠습니다! 죄송합니다 😭

2024-10-08 08:37 UTC, YIMSEBIN commented on src/components/common/Modal/index.tsx
STEP2 클론코딩 프로젝트를 진행할 때 제공해주셨던 코드가 모두 index에서 컴포넌트를 정의하고 있어서 자연스럽게 사용한 것 같습니다. 컴포넌트를 export 하는 파일은 해당 컴포넌트 이름으로 설정하도록 변경하겠습니다!

2024-10-08 08:37 UTC, YIMSEBIN commented on src/components/common/Modal/index.tsx
> +} & React.HTMLAttributes<HTMLDivElement>;
감사합니다 수정하겠습니다!

2024-10-08 08:42 UTC, YIMSEBIN commented on src/components/common/Modal/index.tsx
> +  buttonChildren: ReactNode;
감사합니다! 혹시 Modal.Text 부분의 "."(온점)이 나타내는게 무엇인지 알 수 있을까요?